apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx

spec:
  rules:
    - host: blog.com
      http:
        paths:
          - path: /posts
            backend:
              serviceName: posts
              servicePort: 4000